version: '3'

services:
  frontend:
    build:
      context: .
      target: development
    ports:
      - "3636:3636"
    environment:
      - DATABASE_URL=postgresql://panini:unsecure@db/panini
      - NEXTAUTH_SECRET=unsecure
      - NEXTAUTH_URL=http://panini.tko-aly.localhost
      - USER_SERVICE_URL=http://users.tko-aly.localhost
      - SERVICE_ID=c3e67e6e-0a89-4238-af25-82f84504f584
      - SERVICE_SECRET=unsecure
      - PUBLIC_URL=http://panini.tko-aly.localhost
      - MINIO_ACCESS_KEY=root
      - MINIO_SECRET_KEY=unsecure
      - MINIO_URL=http://minio:9000
      - MINIO_PUBLIC_URL=http://localhost:9000
      - PORT=3636
    volumes:
      - .:/app
    depends_on:
      - db
    command: npm run dev
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: panini
      POSTGRES_PASSWORD: unsecure
  
  minio:
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: unsecure
    ports:
      - 9000:9000
      - 9001:9001
  
  minio-setup:
    image: minio/mc
    depends_on: [minio]
    entrypoint: >
      /bin/sh -c "
      mc config host add docker http://minio:9000 root unsecure;
      mc mb docker/panini-images;
      mc anonymous set download docker/panini-images;
      exit 0;
      "